basePath: /
definitions:
  apperror.ErrorJSON:
    properties:
      developerMessage:
        type: string
      message:
        type: string
    type: object
  endpoints.healthResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.Cat:
    properties:
      age:
        type: integer
      chipNumber:
        type: string
      dateOfAdmissionToShelter:
        type: string
      gender:
        type: string
      nickname:
        type: string
      photoUrl:
        type: string
    type: object
  models.CatChipNumber:
    properties:
      chipNumber:
        type: string
    type: object
  models.CreateCatRequest:
    properties:
      age:
        type: integer
      chipNumber:
        type: string
      dateOfAdmissionToShelter:
        type: string
      gender:
        type: string
      nickname:
        type: string
      photoUrl:
        type: string
    required:
    - nickname
    type: object
  models.CreateGuardianRequest:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      patronymic:
        type: string
      phone:
        type: string
      photoUrl:
        type: string
    type: object
  models.CreateResidentRequest:
    properties:
      VKAlbumUrl:
        type: string
      age:
        type: integer
      aggressiveness:
        type: boolean
      booking:
        type: boolean
      chipNumber:
        type: string
      dateOfAdmissionToShelter:
        type: string
      gender:
        type: string
      guardianId:
        type: integer
      nickname:
        type: string
      photoUrl:
        type: string
    required:
    - nickname
    type: object
  models.Guardian:
    properties:
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      patronymic:
        type: string
      phone:
        type: string
      photoUrl:
        type: string
    type: object
  models.GuardianId:
    properties:
      id:
        type: integer
    type: object
  models.Resident:
    properties:
      VKAlbumUrl:
        type: string
      age:
        type: integer
      aggressiveness:
        type: boolean
      booking:
        type: boolean
      chipNumber:
        type: string
      dateOfAdmissionToShelter:
        type: string
      gender:
        type: string
      guardianId:
        type: integer
      nickname:
        type: string
      photoUrl:
        type: string
    type: object
host: 127.0.0.1:9000
info:
  contact:
    email: levayu22@gmail.com
    name: Lev Yuvenskiy
  title: Cat Shelter CRM
  version: "1.0"
paths:
  /cats:
    get:
      consumes:
      - application/json
      operationId: getCatsList
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cat'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get cats list
      tags:
      - cats
    post:
      consumes:
      - application/json
      operationId: createCat
      parameters:
      - description: Parameters for creating a cat.
        in: body
        name: createCatObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateCatRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CatChipNumber'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Create cat
      tags:
      - cats
  /cats/{chip_number}:
    delete:
      consumes:
      - application/json
      operationId: deleteCat
      parameters:
      - description: Chip number
        in: path
        name: chip_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Delete cat
      tags:
      - cats
    get:
      consumes:
      - application/json
      operationId: getCat
      parameters:
      - description: Chip number
        in: path
        name: chip_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cat'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get cat
      tags:
      - cats
    put:
      consumes:
      - application/json
      operationId: updateCat
      parameters:
      - description: Chip number
        in: path
        name: chip_number
        required: true
        type: string
      - description: Parameters for updating a cat.
        in: body
        name: createCatObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateCatRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Update cat
      tags:
      - cats
  /guardians:
    get:
      consumes:
      - application/json
      operationId: getGuardiansList
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Guardian'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get guardians list
      tags:
      - guardians
    post:
      consumes:
      - application/json
      operationId: createGuardian
      parameters:
      - description: Parameters for creating a guardian.
        in: body
        name: createGuardianObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateGuardianRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.GuardianId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Create guardian
      tags:
      - guardians
  /guardians/{id}:
    delete:
      consumes:
      - application/json
      operationId: deleteGuardian
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Delete guardian
      tags:
      - guardians
    get:
      consumes:
      - application/json
      operationId: getGuardian
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Guardian'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get guardian
      tags:
      - guardians
    put:
      consumes:
      - application/json
      operationId: updateGuardian
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Parameters for updating a guardian.
        in: body
        name: createGuardianObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateGuardianRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Update guardian
      tags:
      - guardians
  /health:
    get:
      consumes:
      - application/json
      operationId: health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoints.healthResponse'
      summary: Health check
      tags:
      - health
  /residents:
    get:
      consumes:
      - application/json
      operationId: getResidentsList
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Resident'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get residents list
      tags:
      - residents
    post:
      consumes:
      - application/json
      operationId: createResident
      parameters:
      - description: Parameters for creating a resident.
        in: body
        name: createResidentObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateResidentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CatChipNumber'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Create resident
      tags:
      - residents
  /residents/{chip_number}:
    delete:
      consumes:
      - application/json
      operationId: deleteResident
      parameters:
      - description: Chip number
        in: path
        name: chip_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Delete resident
      tags:
      - residents
    get:
      consumes:
      - application/json
      operationId: getResident
      parameters:
      - description: Chip number
        in: path
        name: chip_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Resident'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get resident
      tags:
      - residents
    put:
      consumes:
      - application/json
      operationId: updateResident
      parameters:
      - description: Chip number
        in: path
        name: chip_number
        required: true
        type: string
      - description: Parameters for updating a resident.
        in: body
        name: createResidentObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateResidentRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Update resident
      tags:
      - residents
swagger: "2.0"
