name: Go

on: push

jobs:
 #  build:
 #    runs-on: ubuntu-latest
 #    steps:
 #    - name: Checkout
 #      uses: actions/checkout@v3
 #
 #    - name: Set up Go
 #      uses: actions/setup-go@v4
 #      with:
 #        go-version: '1.20'
 #
 #    - name: Build
 #      run: make build
 # 
 #  lint:
 #    runs-on: ubuntu-latest
 #    needs: [build]
 #    steps:
 #    - name: Checkout
 #      uses: actions/checkout@v3
 #
 #    - name: Set up Go
 #      uses: actions/setup-go@v4
 #      with:
 #        go-version: '1.20'
 #
 #    - name: Install tools
 #      run: make gotools
 #
 #    - name: Gen mocks
 #      run: make mocks
 #
 #    - name: Lint
 #      run: make lint
 #        
 #  unit-tests:
 #    runs-on: ubuntu-latest
 #    needs: [lint]
 #    steps:
 #    - name: Checkout
 #      uses: actions/checkout@v3
 #
 #    - name: Set up Go
 #      uses: actions/setup-go@v4
 #      with:
 #        go-version: '1.20'
 #
 #    - name: Install tools
 #      run: make gotools
 #
 #    - name: Gen mocks
 #      run: make mocks
 #
 #    - name: Unit tests
 #      run: make test
 #        
  e2e-tests:
    runs-on: ubuntu-latest
    # needs: [lint]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Init database
      run: make init-db
 
    - name: Run docker compose
      continue-on-error: true
      run: docker compose -f docker-compose.ci.yaml up --build ci-e2e-tests-client --exit-code-from ci-e2e-tests-client
        
    - name: Stop docker compose
      run: docker compose -f docker-compose.ci.yaml down
